In [ ]:
import pandas as pd

Task 1

Read the Population dataset from the CSV file.

Hint:

● Use the pandas library.

● Display the first five rows.

● Check the shape and data types.

In [ ]:
population = pd.read_csv('/content/population.csv')

In [ ]:
population.head(5)

         country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525

In [ ]:
population.shape

(25, 2)

In [ ]:
population.dtypes

country       object
population     int64
dtype: object

##Task 2
Read the GDP dataset from the Excel file.

Hint:

● Use the appropriate pandas function.

● Display column names and data types.

In [ ]:
df_gdp =pd.read_excel("/content/gdp.xlsx")

In [ ]:
print(df_gdp.dtypes)

Country    object
GDP         int64
dtype: object

##Task 3
Read the Internet Users dataset from the JSON file.

Hint:

● Use either the json module or pandas.

● Convert the data into a DataFrame.

In [ ]:
net_users =pd.read_json("internet_users.json")

In [ ]:
net_users

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

Task 4
Read the Literacy Rate dataset from the XML file.

Hint:

● Use xml.etree.ElementTree or pandas.read_xml().

● Extract all required fields into a DataFrame.

In [ ]:
df_lit = pd.read_xml("/content/literacy_rate.xml")

In [ ]:
df_lit

              name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

## Task 5
Explore each dataset.
Find the following:

● Number of rows

● Number of columns

● Column names

● Data types

● Missing values

● Duplicate records

population

In [ ]:
# Number of row
len(population)

25

In [ ]:
# Number of columns
len(population.columns)

2

In [ ]:
#column names
population.columns

Index(['country', 'population'], dtype='object')

In [ ]:
#Data types
population.dtypes

country       object
population     int64
dtype: object

In [ ]:
#Missing values
population.isnull().sum()

country       0
population    0
dtype: int64

In [ ]:
# Duplicate records
population.duplicated().sum()

np.int64(0)

GDP

In [ ]:
print(len(df_gdp))
print(len(df_gdp.columns))
print(df_gdp.columns)
print(df_gdp.dtypes)
print(df_gdp.isnull().sum())
print(df_gdp.duplicated().sum())

25
2
Index(['Country', 'GDP'], dtype='object')
Country    object
GDP         int64
dtype: object
Country    0
GDP        0
dtype: int64
0

In [ ]:
print(len(net_users))
print(len(net_users.columns))
print(net_users.columns)
print(net_users.dtypes)
print(net_users.isnull().sum())
print(net_users.duplicated().sum())

25
2
Index(['country', 'internet_users'], dtype='object')
country           object
internet_users     int64
dtype: object
country           0
internet_users    0
dtype: int64
0

In [ ]:
# literacy_users
print(len(df_lit))
print(len(df_lit.columns))
print(df_lit.columns)
print(df_lit.dtypes)
print(df_lit.isnull().sum())
print(df_lit.duplicated().sum())

25
2
Index(['name', 'literacy_rate'], dtype='object')
name              object
literacy_rate    float64
dtype: object
name             0
literacy_rate    0
dtype: int64
0

## Task 6
Rename columns wherever necessary so that all datasets have a common column name for merging.

Hint:

● Example: Country → country

In [ ]:
population.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     25 non-null     object
 1   population  25 non-null     int64
dtypes: int64(1), object(1)
memory usage: 532.0+ bytes

In [ ]:
df_gdp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  25 non-null     object
 1   GDP      25 non-null     int64
dtypes: int64(1), object(1)
memory usage: 532.0+ bytes

In [ ]:
net_users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   country         25 non-null     object
 1   internet_users  25 non-null     int64
dtypes: int64(1), object(1)
memory usage: 532.0+ bytes

In [ ]:
df_lit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           25 non-null     object
 1   literacy_rate  25 non-null     float64
dtypes: float64(1), object(1)
memory usage: 532.0+ bytes

In [ ]:
df_lit = df_lit.rename(columns={'name':'country'})

In [ ]:
df_gdp = df_gdp.rename(columns={'Country': 'country'})

In [ ]:
df_lit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   country        25 non-null     object
 1   literacy_rate  25 non-null     float64
dtypes: float64(1), object(1)
memory usage: 532.0+ bytes

In [ ]:
df_gdp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   country  25 non-null     object
 1   GDP      25 non-null     int64
dtypes: int64(1), object(1)
memory usage: 532.0+ bytes

## Task 7
Convert the required columns into appropriate numeric data types.

In [ ]:
# every numeric columns have numeric datatypes

## Task 8
Merge all four datasets into one DataFrame.

Hint:

● Use the common column (country)

● Choose an appropriate join method.

In [ ]:
merged_df = population.merge(df_gdp, on='country', how='outer') \
               .merge(net_users, on='country', how='outer') \
               .merge(df_lit, on='country', how='outer')

In [ ]:
merged_df

           country  population       GDP  internet_users  literacy_rate
0        Argentina    45195774    640000        41000000           99.1
1        Australia    25687041   1880000        24000000           99.0
2           Brazil   212559417   2330000       181000000           93.2
3           Canada    38005238   2250000        36000000           99.0
4            China  1411778724  19230000      1080000000           97.2
5           France    65273511   3211000        62000000           99.0
6          Germany    83240525   4744000        79000000           99.0
7            India  1380004385   4187000       850000000           77.7
8        Indonesia   273523615   1500000       212000000           96.0
9            Italy    60461826   2420000        56000000           99.0
10           Japan   125836021   4180000       118000000           99.0
11          Mexico   128932753   1810000       102000000           95.4
12     Netherlands    17441139   1150000        17000000           99.0
13          Norway     5421241    580000         5300000          100.0
14          Russia   145934462   2200000       125000000           99.7
15    Saudi Arabia    34813871   1100000        34000000           97.3
16       Singapore     5850342    530000         5600000           97.5
17    South Africa    59308690    410000        43000000           95.0
18     South Korea    51780579   1800000        50000000           98.8
19           Spain    46754778   1710000        44000000           98.6
20          Sweden    10353442    650000        10100000           99.0
21     Switzerland     8654622    940000         8500000           99.0
22          Turkey    84339067   1350000        69000000           96.7
23  United Kingdom    67886011   3839000        66000000           99.0
24   United States   331002651  30500000       312000000           99.0

## Task 9
Create the following calculated columns:

1. Internet Penetration (%)

2. GDP Per Capita

Hint:

Round the calculated values to two decimal places.

In [ ]:
merged_df["internet_penetration (%)"] =(merged_df["internet_users"] / merged_df["population"] * 100)

In [ ]:
merged_df["GDP_Per_Capita"] = (merged_df["GDP"] * 1000000 / merged_df["population"])

In [ ]:
merged_df.head()

,country,population,GDP,internet_users,literacy_rate,internet_penetration (%),GDP_Per_Capita
0,Argentina,45195774,640000,41000000,99.1,90.716446,14160.615990
1,Australia,25687041,1880000,24000000,99.0,93.432326,73188.655712
2,Brazil,212559417,2330000,181000000,93.2,85.152661,10961.640904
3,Canada,38005238,2250000,36000000,99.0,94.723785,59202.365737
4,China,1411778724,19230000,1080000000,97.2,76.499240,13621.114749

## Task 10
Create a SQLite database. Store the final merged dataset into a table named
‘country_statistics’

Hint:

● Use the sqlite3 library.

● Load the DataFrame using pandas.

In [ ]:
import sqlite3

In [ ]:
conn =sqlite3.connect("country_statistics.db")
merged_df.to_sql("country_statistics",conn,
              if_exists = "replace",
              index = False
              )
conn.close()

In [ ]:
conn = sqlite3.connect("country_statistics.db")
df = pd.read_sql("SELECT * FROM country_statistics", conn)
conn.close()
df.head()

,country,population,GDP,internet_users,literacy_rate,internet_penetration (%),GDP_Per_Capita
0,Argentina,45195774,640000,41000000,99.1,90.716446,14160.615990
1,Australia,25687041,1880000,24000000,99.0,93.432326,73188.655712
2,Brazil,212559417,2330000,181000000,93.2,85.152661,10961.640904
3,Canada,38005238,2250000,36000000,99.0,94.723785,59202.365737
4,China,1411778724,19230000,1080000000,97.2,76.499240,13621.114749

## Task 11
Verify that the data has been loaded successfully.

Hint:

Retrieve the first five records from the SQLite table.

In [ ]:
df.head(5)

,country,population,GDP,internet_users,literacy_rate,internet_penetration (%),GDP_Per_Capita
0,Argentina,45195774,640000,41000000,99.1,90.716446,14160.615990
1,Australia,25687041,1880000,24000000,99.0,93.432326,73188.655712
2,Brazil,212559417,2330000,181000000,93.2,85.152661,10961.640904
3,Canada,38005238,2250000,36000000,99.0,94.723785,59202.365737
4,China,1411778724,19230000,1080000000,97.2,76.499240,13621.114749

## Data Analysis Using Pandas

1. List the Top 5 countries by GDP

In [ ]:
merged_df.nlargest(5,"GDP")[['country','GDP']]

          country       GDP
24  United States  30500000
4           China  19230000
6         Germany   4744000
7           India   4187000
10          Japan   4180000

2. List the Top 5 countries by population.

In [ ]:
merged_df.nlargest(5,"population")[['country','population']]

          country  population
4           China  1411778724
7           India  1380004385
24  United States   331002651
8       Indonesia   273523615
2          Brazil   212559417

3. Calculate the average literacy rate.

In [ ]:
merged_df['literacy_rate'].mean()

np.float64(97.24799999999999)

4. List all countries having a literacy rate greater than 90%.

In [ ]:
merged_df[merged_df['literacy_rate']>90][['country','literacy_rate' ]]

           country  literacy_rate
0        Argentina           99.1
1        Australia           99.0
2           Brazil           93.2
3           Canada           99.0
4            China           97.2
5           France           99.0
6          Germany           99.0
8        Indonesia           96.0
9            Italy           99.0
10           Japan           99.0
11          Mexico           95.4
12     Netherlands           99.0
13          Norway          100.0
14          Russia           99.7
15    Saudi Arabia           97.3
16       Singapore           97.5
17    South Africa           95.0
18     South Korea           98.8
19           Spain           98.6
20          Sweden           99.0
21     Switzerland           99.0
22          Turkey           96.7
23  United Kingdom           99.0
24   United States           99.0

5. List all countries having an internet penetration greater than 70%.

In [ ]:
merged_df[merged_df['internet_penetration (%)']>70][['country','internet_penetration (%)' ]]

           country  internet_penetration (%)
0        Argentina                 90.716446
1        Australia                 93.432326
2           Brazil                 85.152661
3           Canada                 94.723785
4            China                 76.499240
5           France                 94.984932
6          Germany                 94.905696
8        Indonesia                 77.507019
9            Italy                 92.620425
10           Japan                 93.772832
11          Mexico                 79.111008
12     Netherlands                 97.470698
13          Norway                 97.763593
14          Russia                 85.654888
15    Saudi Arabia                 97.662222
16       Singapore                 95.720900
17    South Africa                 72.502023
18     South Korea                 96.561300
19           Spain                 94.108029
20          Sweden                 97.552099
21     Switzerland                 98.213417
22          Turkey                 81.812620
23  United Kingdom                 97.221797
24   United States                 94.259064

6. List the Top 5 countries by GDP per capita.

In [ ]:
merged_df.nlargest(5, "GDP_Per_Capita")[["country","GDP_Per_Capita"]]

          country  GDP_Per_Capita
21    Switzerland   108612.484751
13         Norway   106986.573738
24  United States    92144.277116
16      Singapore    90592.994392
1       Australia    73188.655712

7. Calculate the total population represented in the dataset.

In [ ]:
merged_df['population'].sum()

np.int64(4720039725)

8. Calculate the average internet penetration across all countries.

In [ ]:
merged_df['internet_penetration (%)'].mean()

np.float64(89.6609210897238)

9. Identify the country having the highest number of internet users.

In [ ]:
merged_df.loc[merged_df["internet_users"].idxmax(),['country','internet_users']]

country                China
internet_users    1080000000
Name: 4, dtype: object

10. Find the correlation between Literacy Rate and Internet Penetration.

In [ ]:
merged_df['literacy_rate'].corr(merged_df['internet_penetration (%)'])

np.float64(0.7727536531179539)

##Data Analysis Using SQL

11. Display the Top 5 countries by GDP.

In [ ]:
# Display the Top 5 countries by GDP. using sqlite
conn=sqlite3.connect('country_statistics.db')

pd.read_sql("""
SELECT country, GDP
FROM country_statistics
ORDER BY GDP DESC
LIMIT 5
""", conn)

         country       GDP
0  United States  30500000
1          China  19230000
2        Germany   4744000
3          India   4187000
4          Japan   4180000

12. Find the average literacy rate.

In [ ]:
pd.read_sql("""
SELECT AVG(literacy_rate) AS
average_litracy_rate
from country_statistics
""", conn)

   average_litracy_rate
0                97.248

13. Display all countries having literacy rate above 90%.

In [ ]:
pd.read_sql(
    """
SELECT country, literacy_rate
FROM country_statistics
WHERE literacy_rate > 90
ORDER BY literacy_rate DESC
""",
    conn,
)

           country  literacy_rate
0           Norway          100.0
1           Russia           99.7
2        Argentina           99.1
3        Australia           99.0
4           Canada           99.0
5           France           99.0
6          Germany           99.0
7            Italy           99.0
8            Japan           99.0
9      Netherlands           99.0
10          Sweden           99.0
11     Switzerland           99.0
12  United Kingdom           99.0
13   United States           99.0
14     South Korea           98.8
15           Spain           98.6
16       Singapore           97.5
17    Saudi Arabia           97.3
18           China           97.2
19          Turkey           96.7
20       Indonesia           96.0
21          Mexico           95.4
22    South Africa           95.0
23          Brazil           93.2

14. Find the Top 5 countries with the highest internet penetration.

In [ ]:
pd.read_sql(
    """
SELECT country, `internet_penetration (%)`
FROM country_statistics
ORDER BY `internet_penetration (%)` DESC
LIMIT 5
""",
    conn,
)

        country  internet_penetration (%)
0   Switzerland                 98.213417
1        Norway                 97.763593
2  Saudi Arabia                 97.662222
3        Sweden                 97.552099
4   Netherlands                 97.470698

15. #Calculate the total population.

In [ ]:
pd.read_sql(
    """
SELECT SUM(population) AS total_population
FROM country_statistics
""",
    conn,
)

   total_population
0        4720039725

16. Find the country with the highest GDP per capita.

In [ ]:
pd.read_sql(
    """
SELECT country, GDP_Per_Capita
FROM country_statistics
ORDER BY GDP_Per_Capita DESC
LIMIT 1
""",
    conn,
)

       country  GDP_Per_Capita
0  Switzerland   108612.484751

17. Export the final merged dataset as a CSV file

In [ ]:
df = pd.read_sql("SELECT * FROM country_statistics", conn)

df.to_csv("final_merged_dataset.csv", index=False)

print("CSV file exported successfully!")

CSV file exported successfully!

18. Sort the dataset in descending order of GDP per Capita and display the Top 10 countries.

In [ ]:
pd.read_sql( """
SELECT country,  GDP_Per_Capita
FROM country_statistics
ORDER BY  GDP_Per_Capita DESC
LIMIT 10
""", conn)

          country  GDP_Per_Capita
0     Switzerland   108612.484751
1          Norway   106986.573738
2   United States    92144.277116
3       Singapore    90592.994392
4       Australia    73188.655712
5     Netherlands    65936.060713
6          Sweden    62781.053876
7          Canada    59202.365737
8         Germany    56991.471402
9  United Kingdom    56550.678755

Write a short summary (5–6 points) explaining your ETL process, including:

● Data sources used

● Data cleaning steps

● Transformations performed

● Database loading process

● Key insights obtained from the analysis

In [ ]:
# Data sources used: raw data is collected from many sources including CSV files, API data, SQL databases,etc.
# Data cleaning steps: Removing duplicates, handling missing values, etc are included in data cleaning.
# Transformations performed: data is transformed into ready to use forms after some operations
# Database loading process: load the transformed data into databases
# key insights ETL enables automation and error handling